mybar:
   name: 张三
   arrs: 赵,钱,孙,李
   nameList:
   -  name: 刘
      value: 刘备
   -  name: 张
      value: 张飞
   barNameList:
   - 早退次数
   - 迟到次数
   - 旷工天数
   map:
      key1: 曹操
      key2: 曹丕
      key3: 曹植
report:
   config:
      ccwhoisd:
         ccwhoisd:
            metrics: domain.keyword,client.keyword
            exclude: 218.241.97.201,218.241.97.202,218.241.115.188,218.241.98.196,218.241.102.66,218.241.102.67
         ccwhoisweb:
            include: 218.241.97.201,218.241.97.202
            metrics: domain.keyword
         monitor:
            include: 218.241.115.188,218.241.98.196,218.241.102.66,218.241.102.677